name: Build & Deploy
on: [ push ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.x
        id: go

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build
        run: |
          CGO_ENABLED=0 go build -v -trimpath . -o icppp

      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: icppp
          path: /home/runner/work/icppp/icppp

  dockerfile:
    name: Build Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@master
        with:
          name: icppp
          path: /home/runner/work/icppp/icppp

      - name: Settings
        run: |
          chmod +x ./icppp
          ls -l

      - name: Build & Publish to Registry
        uses: wuhan005/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.hub.docker.com
          repository: registry.hub.docker.com/wuhan005/icppp
          tag_format: "%YYYY%_%MM%_%DD%_%H%%m%%s%"
          auto_tag: true