name: LSIF
on:
  push:
    paths:
      - '**.go'
      - '.github/workflows/lsif.yml'
jobs:
  lsif-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Generate LSIF data
        uses: sourcegraph/lsif-go-action@master
      - name: Upload LSIF data to sourcegraph.com
        continue-on-error: true
        uses: docker://sourcegraph/src-cli:latest
        with:
          args: lsif upload -github-token=${{ secrets.GITHUB_TOKEN }}
